export const articles = [
  {
    slug: "connecticut-hvac-recovered-84k",
    category: "Case Studies",
    tag: "CASE STUDY",
    title: "How a Connecticut HVAC Company Recovered $84K in One Quarter",
    excerpt: "Pinnacle Heating & Cooling was answering roughly 60% of inbound calls. The other 40% were gone. Nova Systems deployed AI call handling and Nova Pulse monitoring — and the results changed everything.",
    readTime: "6 min read",
    result: "+$84,000 revenue recovered",
    featured: true,
    content: [
      { heading: "The Problem", body: "Pinnacle Heating & Cooling had been in business for 11 years. Their work was excellent — five-star reviews, loyal customers, solid referrals. But owner Mike DiLorenzo had a nagging sense that calls were slipping through. A quick audit confirmed his worst fear: 40% of inbound calls were going unanswered, especially during peak hours and after 5pm. At an average ticket of $380, those missed calls were costing Pinnacle over $2,000 per week." },
      { heading: "The Diagnosis", body: "When we ran a full revenue leak audit, the picture got clearer. Pinnacle had no after-hours system, no CRM, and follow-up was entirely manual — meaning leads that called back got the same experience as new callers. There was no tracking, no automation, and no way for Mike to see what was happening in real time. He was running blind." },
      { heading: "The Solution", body: "Nova Systems deployed a three-part system. First, AI call handling was set up to answer every inbound call 24/7, qualify the caller, and book them directly into Pinnacle's schedule. Second, Nova Pulse was configured to track every call, every lead, and every outcome — giving Mike a live dashboard he could check from his phone. Third, an automated follow-up sequence was built for every missed call and web form submission, ensuring no lead ever fell silent." },
      { heading: "The Results", body: "Within 90 days, Pinnacle's call answer rate went from 60% to 97%. Lead-to-booking conversion improved by 34%. And total revenue recovered in that quarter came to $84,320 — money that had previously been walking out the door. Mike now checks his Nova Pulse dashboard every morning before his first job." },
      { heading: "What This Means for You", body: "If you're a service business with inbound calls and you're not capturing every one of them, you're leaving money on the table. The math is simple: missed calls × average ticket × weeks = your annual leak. Nova Systems closes that leak. Book a free audit and we'll show you exactly what you're losing." },
    ],
  },
  {
    slug: "50000-mistake-missing-5-calls-per-day",
    category: "Revenue Leaks",
    tag: "REVENUE LEAKS",
    title: "The $50,000 Mistake: What Happens When You Miss 5 Calls Per Day",
    excerpt: "If your business misses just 5 calls per day with an average ticket of $200, you're walking away from over $50,000 per year. And that's before counting the compounding effect of those customers going to your competitor.",
    readTime: "4 min read",
    result: null,
    featured: false,
    content: [
      { heading: "The Math No One Wants to Do", body: "Let's keep this simple. If your business misses 5 calls per day, and your average service ticket is $200, that's $1,000 in potential revenue lost daily. Over a 5-day work week, that's $5,000. Over 50 weeks, that's $250,000 per year — assuming every missed call was a buyer, which of course isn't true. But even at a conservative 20% conversion rate, you're still leaving $50,000 on the table. Every year. From just 5 missed calls a day." },
      { heading: "The Compound Effect", body: "Here's what makes it worse: those callers don't disappear. They call your competitor. And if your competitor answers — and delivers good service — you've just handed them a customer who might buy from them again, refer their friends, and leave them a five-star review. The cost of a single missed call isn't just the ticket you lost. It's the lifetime value of a customer you gave away." },
      { heading: "Why Businesses Miss Calls", body: "It's almost never laziness or neglect. It's capacity. Your team is on a job. It's after hours. It's lunchtime. It's a busy Tuesday and three calls come in at once. This is the reality of running a service business — and it's exactly the problem that AI call handling was built to solve. When technology answers every call, qualifies the caller, and books them while your team is on the job, nothing falls through the cracks." },
      { heading: "The Fix", body: "Nova Systems deploys AI call handling that answers 100% of your inbound calls, 24/7. Combined with Nova Pulse, every call is logged, tracked, and reported — so you know exactly what came in, what got answered, and what happened next. The investment pays for itself within the first week of deployment for most clients." },
    ],
  },
  {
    slug: "revenue-leak-audit-10-point-checklist",
    category: "Guides",
    tag: "GUIDE",
    title: "The Local Business Revenue Leak Audit: A 10-Point Checklist",
    excerpt: "Before you can fix a revenue leak, you need to know where it is. This 10-point checklist walks through every point of failure in the typical local business sales process — from first contact to closed deal.",
    readTime: "8 min read",
    result: null,
    featured: false,
    content: [
      { heading: "Why Audits Matter", body: "Revenue leaks are invisible by design. They don't show up as a line item on your P&L. They show up as a slightly lower conversion rate, a slightly higher cost per acquisition, and a nagging sense that things should be growing faster than they are. The audit below is designed to surface these leaks so you can fix them." },
      { heading: "1. Call Answer Rate", body: "What percentage of your inbound calls get answered by a human or AI within 30 seconds? Anything below 90% is a revenue leak. Run this report on your phone system for the last 30 days." },
      { heading: "2. After-Hours Coverage", body: "What happens when someone calls at 7pm or on a Saturday? If the answer is 'voicemail,' you're leaking every caller who doesn't leave a message — which is most of them." },
      { heading: "3. First Response Time", body: "How long does it take your team to respond to a web form, email inquiry, or missed call? Leads contacted within 5 minutes are 21x more likely to convert. If your average response time is more than an hour, you have a serious leak." },
      { heading: "4. Lead Source Tracking", body: "Do you know which marketing channel drives your best leads? If not, you're likely spending money on channels that don't convert and underinvesting in ones that do." },
      { heading: "5. CRM Usage", body: "Is every lead entered into a CRM? If follow-up lives in someone's head or a paper notepad, leads are falling through the cracks every week." },
      { heading: "6. Follow-Up Sequence", body: "How many times does your team follow up with a lead before marking them lost? The average sale requires 5+ touchpoints. Most businesses give up after 1-2." },
      { heading: "7. Booking Rate", body: "Of the leads you speak with, what percentage book an appointment or request a quote? If this number is below 40%, you have a conversion problem — not a traffic problem." },
      { heading: "8. No-Show Rate", body: "What percentage of booked appointments actually show up? High no-show rates indicate a weak confirmation and reminder process." },
      { heading: "9. Close Rate", body: "Of the appointments that show up, what percentage close into paying customers? Tracking this number is essential to knowing whether your sales process needs work." },
      { heading: "10. Repeat Business Rate", body: "What percentage of customers come back for a second purchase? Repeat customers cost nothing to acquire. If you're not actively marketing to past customers, you're leaving money on the table." },
      { heading: "Next Step", body: "Nova Systems runs this audit for free as part of every demo call. We'll pull your real numbers and show you exactly where you're losing revenue — and how much." },
    ],
  },
  {
    slug: "why-slow-followup-costs-30-percent",
    category: "Revenue Leaks",
    tag: "REVENUE LEAKS",
    title: "Why Local Service Businesses Lose 30% of Revenue to Slow Follow-Up",
    excerpt: "Leads contacted within 5 minutes are 21x more likely to convert than those contacted after 30 minutes. Most local businesses respond in hours — or not at all.",
    readTime: "5 min read",
    result: null,
    featured: false,
    content: [
      { heading: "Speed Is a Competitive Advantage", body: "In service businesses, the first vendor to respond usually wins the job. This isn't because they're better — it's because the customer was ready to buy in that moment, and you were there. According to a study by the Harvard Business Review, companies that contact leads within an hour are 7x more likely to have meaningful conversations than those who wait even 60 minutes." },
      { heading: "The 5-Minute Window", body: "For local service businesses, the window is even tighter. When someone searches for an HVAC company, calls three numbers, and the first one picks up — they rarely call the other two. Speed isn't just an advantage; it's the entire game. The 5-minute follow-up rule isn't a best practice; it's a survival strategy." },
      { heading: "Why Businesses Are Slow", body: "It's almost never intentional. Owners are on jobs. Staff is handling customers. Nobody sees the email come in until they're back at the desk. By then, the lead has already booked with someone else. The solution isn't to hire more people — it's to automate the first response so it's instant, every time." },
      { heading: "What Automation Looks Like", body: "Nova Systems implements automated first-touch sequences that fire within seconds of a new lead arriving. An email goes out. A text message is sent. If the lead came in as a missed call, an AI texts them back within 30 seconds. The first human doesn't need to be available — the system handles the response, books the appointment, and notifies the team." },
      { heading: "The Revenue Impact", body: "For a business generating $500K per year in revenue, a 30% improvement in follow-up speed typically translates to $50K-$100K in additional annual revenue — from leads that were already coming in. No new marketing spend required." },
    ],
  },
  {
    slug: "luxe-realty-22-to-67-percent-conversion",
    category: "Case Studies",
    tag: "CASE STUDY",
    title: "Luxe Realty: From 22% to 67% Lead Conversion in 60 Days",
    excerpt: "Luxe Realty had a lead problem — not a traffic problem. Leads were coming in but follow-up was inconsistent and manual. Nova Systems rebuilt their CRM pipeline and automated every touchpoint.",
    readTime: "7 min read",
    result: "22% to 67% conversion rate",
    featured: false,
    content: [
      { heading: "The Situation", body: "Luxe Realty was spending $8,000 per month on Google Ads and Facebook campaigns. Leads were coming in — about 120 per month. But their conversion rate was stuck at 22%, and the sales team couldn't figure out why. When we audited their process, the issue was obvious: follow-up was entirely manual and inconsistent." },
      { heading: "The Audit", body: "Of 120 leads per month, only 85 were being contacted within 24 hours. Of those, about 40 received more than one follow-up attempt. The rest were marked 'no response' after a single call or email and never touched again. The math was brutal: Luxe was converting 26 leads per month out of a possible 120 — and paying $308 per converted lead." },
      { heading: "The System We Built", body: "Nova Systems implemented a full CRM pipeline with automated follow-up sequences for every lead stage. New leads received a text within 60 seconds, an email within 2 minutes, and a personalized voicemail drop within 24 hours. If a lead didn't respond, an automated sequence continued for 14 days with progressively softer messaging. No lead was ever manually 'closed' without at least 7 touchpoints." },
      { heading: "60-Day Results", body: "Within 60 days, Luxe's contact rate went from 71% to 96%. Their follow-up rate went from 33% to 100%. And their conversion rate climbed from 22% to 67%. They're now converting 80 leads per month from the same 120 — and their cost per converted lead dropped from $308 to $100. Same marketing budget. Triple the output." },
      { heading: "The Lesson", body: "Most businesses with a lead problem actually have a follow-up problem. Traffic and leads are wasted when the back-end process is broken. Nova Systems fixes the back end — and the results speak for themselves." },
    ],
  },
  {
    slug: "5-follow-up-automations-local-business",
    category: "Automation",
    tag: "AUTOMATION",
    title: "5 Follow-Up Automations Every Local Business Needs Right Now",
    excerpt: "Manual follow-up is killing your close rate. Here are the five automation workflows that Nova Systems implements for every client — and how to build them for your specific business.",
    readTime: "6 min read",
    result: null,
    featured: false,
    content: [
      { heading: "Why Automate Follow-Up?", body: "Manual follow-up requires discipline, time, and perfect memory. Your team has none of these in unlimited supply. Automation removes the human variable and ensures every lead gets the same high-quality sequence — every time, without fail." },
      { heading: "1. Missed Call Instant Text", body: "When a call goes unanswered, an automated text fires within 30 seconds: 'Hey, this is [Business Name]! We just missed your call — are you still looking for help with [service]? Reply here and we'll get you sorted right away.' Conversion rate on this single automation averages 18% across our client base." },
      { heading: "2. New Lead Welcome Sequence", body: "When a lead fills out a web form or is added to your CRM, they receive a 5-touch sequence over 7 days: an immediate email, a same-day text, a day-2 follow-up, a day-4 check-in, and a day-7 final reach-out. Each message is personalized to the lead's inquiry." },
      { heading: "3. Appointment Confirmation + Reminder", body: "Every booked appointment receives an instant confirmation email and text. A reminder fires 24 hours before the appointment and again 2 hours before. No-show rates drop by an average of 60% for clients who implement this sequence." },
      { heading: "4. Post-Service Review Request", body: "48 hours after a completed job, an automated text goes out: 'Thank you for choosing [Business]! If you had a great experience, we'd love a quick Google review — it takes 30 seconds and means the world to us. [Link].' Review velocity typically doubles within 30 days." },
      { heading: "5. Reactivation Campaign", body: "Every 90 days, an automated sequence goes out to past customers who haven't booked in over 6 months. Seasonal relevance makes this especially powerful for HVAC, landscaping, and other weather-dependent services. Average reactivation rate: 12-22%." },
      { heading: "Getting Started", body: "These five automations are the foundation of the Nova Systems operating stack. They can be implemented in most CRM platforms — or we build and manage them for you as part of every Nova Systems engagement." },
    ],
  },
  {
    slug: "5-signs-losing-revenue-without-knowing",
    category: "Revenue Leaks",
    tag: "REVENUE LEAKS",
    title: "5 Signs Your Business Is Losing Revenue Without Knowing It",
    excerpt: "Revenue leaks are invisible by design. These five warning signs appear before the revenue disappears — here's how to spot them.",
    readTime: "4 min read",
    result: null,
    featured: false,
    content: [
      { heading: "The Invisible Drain", body: "Revenue leaks don't announce themselves. You don't get a notification when a lead calls and hangs up after four rings. You don't get an alert when a follow-up email never gets sent. The money just quietly disappears — and you chalk it up to 'slow season' or 'tough market.'" },
      { heading: "Sign 1: Your Close Rate Is Flat", body: "If your close rate hasn't improved in 6+ months despite more leads coming in, you're leaking revenue somewhere between first contact and signed contract. More leads with the same conversion rate means your back-end process is the constraint — not your marketing." },
      { heading: "Sign 2: Customers Are Leaving Voicemails", body: "Every voicemail is a lead who didn't get an answer. Most people who leave voicemails also call your competitor. If you're regularly returning voicemails more than 2 hours after they're left, you're losing a significant portion of those callers." },
      { heading: "Sign 3: You Can't Answer 'Where Did That Lead Come From?'", body: "If you can't tell, in real time, which marketing channel drove a lead, you're flying blind. Without attribution, you're probably spending money on low-converting channels and underinvesting in high-converting ones." },
      { heading: "Sign 4: Your Team Is 'Too Busy' to Follow Up", body: "When follow-up depends on whether a team member has bandwidth, follow-up doesn't happen consistently. 'Too busy' is the number one killer of lead conversion in service businesses — and it's completely solvable with automation." },
      { heading: "Sign 5: You Don't Know Your Average Response Time", body: "If you can't tell me how long it takes your team to respond to a new lead, you almost certainly have a response time problem. Best-in-class is under 5 minutes. Industry average is 47 hours. The gap between those two numbers is your competitive opportunity." },
    ],
  },
  {
    slug: "how-to-choose-crm-local-service-business",
    category: "Guides",
    tag: "GUIDE",
    title: "How to Choose the Right CRM for a Local Service Business",
    excerpt: "Most CRMs are built for enterprise sales teams — not for HVAC companies, med spas, or law firms. This guide breaks down what matters for local service businesses.",
    readTime: "9 min read",
    result: null,
    featured: false,
    content: [
      { heading: "The CRM Problem", body: "Walk into any Salesforce or HubSpot demo and you'll see dashboards built for 50-person sales teams with 6-month enterprise deal cycles. That's not your business. If you run an HVAC company, a law firm, or a med spa, you need a CRM built around inbound calls, quick appointments, and repeat service customers — not pipeline stages and quarterly forecasts." },
      { heading: "What Local Businesses Actually Need", body: "The core requirements for a local service business CRM are simple: every inbound call logged automatically, every lead tracked from first contact to closed sale, automated follow-up that doesn't require your team to remember anything, and a mobile-first experience so the owner can check in from the job site." },
      { heading: "The Common Mistakes", body: "Mistake #1: Buying the cheapest option and trying to customize it yourself. CRM configuration is a skill — doing it wrong means your team won't use it. Mistake #2: Buying the most expensive option and using 10% of its features. You're paying for complexity you don't need. Mistake #3: Buying any CRM without an implementation plan. A CRM on a shelf does nothing." },
      { heading: "What to Look For", body: "Look for native phone integration (calls logged automatically), SMS capability built in, appointment scheduling with calendar sync, automated follow-up sequences (not just reminders — actual drip campaigns), a mobile app your team will actually use, and simple reporting that shows you conversion rates and response times in one screen." },
      { heading: "Platforms Worth Considering", body: "For most local service businesses under $2M in revenue, the right CRM is usually one of three options: GoHighLevel (powerful, requires setup), ServiceTitan (purpose-built for trades, expensive), or a custom Nova Systems stack built on proven components tailored to your specific workflow. We'll recommend the right fit based on your business size, tech comfort, and budget during your demo call." },
      { heading: "The Nova Systems Approach", body: "Rather than prescribing a single platform, Nova Systems audits your current workflow and recommends the specific stack that fits your business. We then implement, configure, and train your team — so you actually use it, and it actually produces results." },
    ],
  },
];
