// Generates supabase/sales-team-07-academy-content-migration-standalone.sql from scripts/academy_content/*.
//   node scripts/build_academy_content.mjs
// The migration is idempotent and re-runnable. It only overwrites a program's content while that program is still
// 'pending_owner_review' (or below version 2), so re-running it can never silently change content the owner already approved.
import fs from 'node:fs';
import { programs, toolkit } from './academy_content/index.mjs';
import { validateContent } from './validate_academy_content.mjs';

const problems = validateContent();
if (problems.length) { problems.forEach((p) => console.error(`FAIL — ${p}`)); process.exit(1); }
const dq = (s, tag = 'nv') => { if (String(s).includes(`$${tag}$`)) throw new Error(`text contains the quoting tag $${tag}$`); return `$${tag}$${s}$${tag}$`; };
const arr = (a) => `ARRAY[${a.map((x) => dq(x, 'o')).join(', ')}]::text[]`;
const out = [];
out.push(`-- =============================================================================================
-- Nova Sales Team platform — part 7: ACADEMY v2 CONTENT (10 programs) + Sales Toolkit starter items.
-- GENERATED by scripts/build_academy_content.mjs from scripts/academy_content/*. Do not edit by hand.
-- Additive and re-runnable. Depends on: academy-migration-standalone.sql and sales-team-02 (v2 tables).
--
-- Every program is left at content_review_status = 'pending_owner_review'. Nothing here is "approved": the owner reads and approves each
-- program in Sales Team → Academy before it counts as reviewed. A program's content is only overwritten while it is still pending or
-- below version 2, so re-running this file never changes content the owner already approved.
-- No lesson, question or toolkit item states a price, a revenue figure, a guaranteed outcome or an unapproved turnaround.
-- =============================================================================================
`);
for (const g of programs) {
  out.push(`-- ---------------------------------------------------------------- ${g.slug}
DO $academy$
DECLARE pid uuid; can_write boolean;
BEGIN
  SELECT id, (content_review_status = 'pending_owner_review' OR version < 2) INTO pid, can_write FROM academy_programs WHERE slug = '${g.slug}';
  IF pid IS NULL THEN RAISE NOTICE 'program ${g.slug} not found — run academy-migration-standalone.sql first'; RETURN; END IF;
  IF NOT can_write THEN RAISE NOTICE 'program ${g.slug} content already approved — left unchanged'; RETURN; END IF;
  UPDATE academy_programs SET version = 2, content_review_status = 'pending_owner_review', learning_objectives = ${arr(g.objectives)},
    practical_prompt = ${g.practical ? dq(g.practical.prompt, 'pp') : 'NULL'}, practical_rubric = ${g.practical ? `${dq(JSON.stringify(g.practical.rubric), 'rb')}::jsonb` : "'[]'::jsonb"} WHERE id = pid;`);
  g.lessons.forEach((l, i) => out.push(`  INSERT INTO academy_lessons (program_id, order_index, title, objectives, body) VALUES (pid, ${i + 1}, ${dq(l.title, 't')}, ${arr(l.objectives)}, ${dq(l.body, 'b')})
    ON CONFLICT (program_id, order_index) DO UPDATE SET title = EXCLUDED.title, objectives = EXCLUDED.objectives, body = EXCLUDED.body;`));
  g.questions.forEach((q, i) => out.push(`  INSERT INTO academy_quiz_questions (program_id, order_index, question, choices, correct_index, explanation, critical) VALUES (pid, ${i + 1}, ${dq(q.q, 'q')}, ${dq(JSON.stringify(q.choices), 'c')}::jsonb, ${q.answer}, ${dq(q.why, 'e')}, ${q.critical ? 'true' : 'false'})
    ON CONFLICT (program_id, order_index) DO UPDATE SET question = EXCLUDED.question, choices = EXCLUDED.choices, correct_index = EXCLUDED.correct_index, explanation = EXCLUDED.explanation, critical = EXCLUDED.critical;`));
  g.exercises.forEach((e, i) => out.push(`  INSERT INTO academy_exercises (program_id, order_index, lesson_order, title, prompt, self_check, model_answer) VALUES (pid, ${i + 1}, ${e.lesson_order}, ${dq(e.title, 't')}, ${dq(e.prompt, 'p')}, ${dq(JSON.stringify(e.self_check), 's')}::jsonb, ${dq(e.model_answer, 'm')})
    ON CONFLICT (program_id, order_index) DO UPDATE SET lesson_order = EXCLUDED.lesson_order, title = EXCLUDED.title, prompt = EXCLUDED.prompt, self_check = EXCLUDED.self_check, model_answer = EXCLUDED.model_answer;`));
  out.push(`END
$academy$;
`);
}
out.push(`-- ---------------------------------------------------------------- Sales Toolkit starter items (ALL DRAFT — owner approves each)`);
for (const t of toolkit) {
  out.push(`INSERT INTO sales_toolkit_items (kind, title, body, program_slug, compliance_note, status)
SELECT '${t.kind}', ${dq(t.title, 't')}, ${dq(t.body, 'b')}, ${t.program ? `'${t.program}'` : 'NULL'}, ${dq(t.note, 'n')}, 'draft'
WHERE NOT EXISTS (SELECT 1 FROM sales_toolkit_items WHERE kind = '${t.kind}' AND title = ${dq(t.title, 't')});
`);
}
const file = 'supabase/sales-team-07-academy-content-migration-standalone.sql';
fs.writeFileSync(file, out.join('\n'));
console.log(`wrote ${file} (${(fs.statSync(file).size / 1024).toFixed(0)} KB): ${programs.length} programs, ${programs.reduce((s, g) => s + g.lessons.length, 0)} lessons, ${programs.reduce((s, g) => s + g.questions.length, 0)} questions, ${toolkit.length} toolkit drafts`);
